version: '3'
services: 
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=os-ticket-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
  osticket: 
    image: bynarlogic/osticket
    ports:
      - "5000:80"
volumes:
  mysql_data:
